import React, {useEffect, useState} from 'react';
type D=Record<string,any>;
type Props={revisions:D[],api:(path:string,method?:string,body?:any)=>Promise<any>,run:(fn:()=>Promise<any>,message?:string,close?:boolean)=>Promise<any>,edit:(r:D,c:D)=>void,complete:(r:D)=>void};
const human=(s:string='')=>s.replaceAll('_',' ');
const val=(c:D)=>c.nominal==null?c.raw||c.label:`${c.type==='diameter'?'Ø':''}${c.nominal} [${c.lower_tolerance}, +${c.upper_tolerance}] ${c.unit}`;

export function SourceCanvas({revision,characteristic,zoom=1,onPosition}:{revision:D,characteristic?:D,zoom?:number,onPosition?:(x:number,y:number)=>void}){
 const [size,setSize]=useState({w:842,h:595});const [error,setError]=useState(false);
 const [manualPage,setManualPage]=useState<number|null>(null);const page=manualPage??characteristic?.source_page??1;const box=page===(characteristic?.source_page||1)?characteristic?.source_location?.bbox:null;
 useEffect(()=>setManualPage(null),[revision.id,characteristic?.characteristic_id,characteristic?.source_page]);
 useEffect(()=>setError(false),[revision.id,page]);
 if(!['.pdf','.png','.jpg','.jpeg'].includes(revision.suffix))return <div className="source-empty">Structured source: {revision.filename}<p>Source row {characteristic?.source_location?.row||'not specified'}. Download and check the original workbook or document.</p><a href={`/api/v1/revisions/${revision.id}/balloons?format=xlsx`}>Export characteristic list</a></div>;
 return <div className="source-frame"><div className="source-tools"><label>Source page <select aria-label={`Source page revision ${revision.revision}`} value={page} onChange={e=>setManualPage(Number(e.target.value))}>{(revision.pages?.length?revision.pages:[{page:1}]).map((p:D)=><option key={p.page} value={p.page}>{p.page}</option>)}</select></label><small>Inspect every page, including areas with no extracted characteristics.</small></div><div className="source-scroll"><div className="source-canvas" style={{width:100*zoom+'%'}} onClick={e=>{if(!onPosition||page!==characteristic?.source_page)return;const r=e.currentTarget.getBoundingClientRect();onPosition((e.clientX-r.left)/r.width*size.w,(e.clientY-r.top)/r.height*size.h)}}>
 {error?<p role="alert">Source preview unavailable. Check the original file and integrity status.</p>:<img alt={`Controlled revision ${revision.revision}, page ${page}`} src={`/api/v1/revisions/${revision.id}/pages/${page}`} onError={()=>setError(true)} onLoad={e=>{const im=e.currentTarget;const p=revision.pages?.find((p:D)=>p.page===page);setSize({w:p?.width||im.naturalWidth/(revision.suffix==='.pdf'?1.4:1),h:p?.height||im.naturalHeight/(revision.suffix==='.pdf'?1.4:1)})}}/>}
 {!error&&box&&<div className="source-highlight" style={{left:box[0]/size.w*100+'%',top:box[1]/size.h*100+'%',width:(box[2]-box[0])/size.w*100+'%',height:(box[3]-box[1])/size.h*100+'%'}}><span>{characteristic?.characteristic_id} · #{characteristic?.balloon_number||'unassigned'}</span></div>}
 {!error&&page===characteristic?.source_page&&characteristic?.balloon_position&&<div className="source-balloon" style={{left:characteristic.balloon_position.x/size.w*100+'%',top:characteristic.balloon_position.y/size.h*100+'%'}}>{characteristic.balloon_number}</div>}
 </div></div></div>
}

export function VerificationWorkbench({revisions,api,run,edit,complete}:Props){
 const [rid,setRid]=useState('');const [cid,setCid]=useState('');const [filter,setFilter]=useState('ALL');const [zoom,setZoom]=useState(1);const [reason,setReason]=useState('');const [move,setMove]=useState(false);const [number,setNumber]=useState('');
 const r=revisions.find(r=>r.id===rid)||revisions[0];const chars=r?.characteristics||[];const eligible=chars.filter((c:D)=>filter==='ALL'||filter==='LOW'&&c.confidence<.9||filter==='PENDING'&&c.verification_status==='REVIEW_REQUIRED');const c=eligible.find((c:D)=>c.characteristic_id===cid)||eligible[0];
 useEffect(()=>{setNumber(String(c?.balloon_number||''));setMove(false)},[c?.characteristic_id,r?.id]);
 if(!r)return <div className="panel panel-copy">Upload a revision to begin source verification.</div>;
 const filtered=eligible;
 const decision=(decision:string)=>run(()=>api(`/revisions/${r.id}/characteristics/${encodeURIComponent(c.characteristic_id)}/decision`,'POST',{decision,reason,expected_version:r.version}),'Characteristic disposition recorded',false);
 const annotate=(x?:number,y?:number)=>run(()=>api(`/revisions/${r.id}/characteristics/${encodeURIComponent(c.characteristic_id)}/annotation`,'PATCH',{balloon_number:Number(number),reason,expected_version:r.version,...(x===undefined?{}:{x,y})}),'Balloon mapping saved',false);
 return <section className="panel workbench"><div className="workbench-toolbar"><div><h2>Characteristic verification workbench</h2><p>Source evidence → engineering value → accountable human decision</p></div><select aria-label="Verification revision" value={r.id} onChange={e=>{setRid(e.target.value);setCid('')}}>{revisions.map(r=><option value={r.id} key={r.id}>Revision {r.revision} · {r.filename}</option>)}</select><button className="button" onClick={()=>complete(r)}>Confirm completeness</button></div>
 <div className="verification-grid"><div className="source-pane"><div className="source-tools"><strong>Revision {r.revision} · page {c?.source_page||1}</strong><button className="button" onClick={()=>setZoom(Math.max(1,zoom-.25))} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button className="button" onClick={()=>setZoom(Math.min(3,zoom+.25))} aria-label="Zoom in">+</button></div><SourceCanvas revision={r} characteristic={c} zoom={zoom} onPosition={move?(x,y)=>{annotate(x,y);setMove(false)}:undefined}/><div className="source-caption">{move?'Click the source to position this balloon.':c?.source_location?.bbox?'Highlighted region is extraction evidence.':'No bounding box available; verify the original source manually.'}</div><details className="pipeline"><summary>Extraction methods & limitations</summary>{r.pipeline?.map((p:D,i:number)=><p key={i}>{human(p.stage)}: {human(p.status)}</p>)}{r.warnings?.map((w:string,i:number)=><p key={i}>{w}</p>)}</details></div>
 <div className="characteristic-pane"><div className="char-toolbar"><select aria-label="Confidence filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All characteristics ({chars.length})</option><option value="LOW">Confidence below 90%</option><option value="PENDING">Awaiting verification</option></select><button className="button" onClick={()=>edit(r,{characteristic_id:'',label:'',type:'linear',unit:'mm',source_page:1})}>+ Add manually</button></div><div className="characteristic-list">{filtered.map((item:D)=><button className={c?.characteristic_id===item.characteristic_id?'selected':''} key={item.characteristic_id} onClick={()=>setCid(item.characteristic_id)}><span className="char-id">#{item.balloon_number||'?'} · {item.characteristic_id}</span><strong>{item.label}</strong><span className="mono">{val(item)}</span><span className={item.confidence<.9?'confidence-review':'confidence-high'}>{Math.round(item.confidence*100)}% · {human(item.confidence_band||'REVIEW_REQUIRED')}</span><small>{human(item.engine||item.extraction_method)} · {human(item.verification_status)}</small></button>)}</div>
 {c&&<div className="verification-controls"><strong>{c.characteristic_id} · Human review</strong><button className="button" onClick={()=>edit(r,c)}>Edit engineering value</button><label>Decision / annotation reason<textarea aria-label="Verification reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="What was checked against the controlled source?"/></label><div className="review-buttons"><button className="button primary" disabled={reason.length<5} onClick={()=>decision('VERIFIED')}>Verify</button><button className="button" disabled={reason.length<5} onClick={()=>decision('REJECTED')}>Reject extraction</button><button className="button" disabled={reason.length<5} onClick={()=>decision('REVIEW_REQUIRED')}>Flag</button></div><div className="annotation-controls"><label>Balloon #<input aria-label="Balloon number" type="number" min="1" max="9999" value={number} onChange={e=>setNumber(e.target.value)}/></label><button className="button" disabled={reason.length<5||!number} onClick={()=>annotate()}>Renumber</button><button className="button" disabled={reason.length<5||!r.pages?.length} onClick={()=>setMove(!move)}>{move?'Cancel move':'Move balloon'}</button></div><Reconcile key={r.id+':'+c.characteristic_id} revision={r} characteristic={c} api={api} run={run}/><details><summary>Original extraction & correction history</summary><pre>{JSON.stringify({original:c.extracted_original,corrections:c.human_corrections},null,2)}</pre></details></div>}
 </div></div><div className="panel-footer"><span>{r.completeness_verified?'Completeness confirmed by a human':'Full-source completeness review required'}</span><a href={`/api/v1/revisions/${r.id}/balloons?format=xlsx`}>Inspection workbook</a><a href={`/api/v1/revisions/${r.id}/balloons?format=pdf`}>Ballooned PDF</a></div></section>
}

export function RuleEvidence({change}:{change:D}){const risk=change.risk;return <section className="rule-evidence"><h3>{risk.score}/100 — {risk.level} <small>RULE-BASED · {risk.rule_version||'legacy; reanalyze'}</small></h3>{change.metrics?.band_reduction_percent!=null&&<p className="calculation">CALCULATED · Band {change.metrics.old_tolerance_band} → {change.metrics.new_tolerance_band} {change.new?.unit} · {change.metrics.band_reduction_percent}% reduction</p>}<div className="score-contributors">{risk.contributors?.map((r:D)=><div key={r.rule_id}><code>{r.rule_id}</code><span>{r.reason}</span><b>+{r.points}</b></div>)}</div>{risk.uncapped_score>100&&<p>Raw score {risk.uncapped_score}; displayed score capped at 100. This is a priority score, not a failure probability.</p>}<details><summary>Required reviews with evidence ({risk.recommendations?.length||0})</summary>{risk.recommendations?.map((r:D,i:number)=><article key={i}><strong>{r.title}</strong><p>{r.why}</p><small>{r.rule_id} · {r.engine} · {Math.round(r.confidence*100)}% extraction confidence · {r.source.characteristic_id}, page {r.source.page}</small></article>)}</details></section>}

export function EngineeringComparison({current,revisions,onReview}:{current:D,revisions:D[],onReview:(c:D)=>void}){
 const [id,setId]=useState('');const [filter,setFilter]=useState('ALL');const [zoom,setZoom]=useState(1);const changes=current.changes.filter((c:D)=>filter==='ALL'||filter==='CRITICAL'&&c.risk.level==='CRITICAL'||filter==='TOLERANCE'&&['TIGHTENED','RELAXED'].includes(c.type)||c.type===filter);const c=changes.find((c:D)=>c.id===id)||changes[0];const a=revisions.find(r=>r.id===current.old_revision_id);const b=revisions.find(r=>r.id===current.new_revision_id);
 return <section className="panel comparison-workspace"><div className="workbench-toolbar"><h2>Engineering revision comparison</h2><select aria-label="Change filter" value={filter} onChange={e=>setFilter(e.target.value)}>{['ALL','CRITICAL','TOLERANCE','ADDED','REMOVED','GDT_CHANGE','MATERIAL_CHANGE','SPECIFICATION_CHANGE','PROCESS_CHANGE'].map(f=><option key={f}>{f}</option>)}</select><button className="button" onClick={()=>setZoom(zoom===1?1.75:1)}>{zoom===1?'Zoom drawings':'Fit drawings'}</button></div><div className="comparison-three"><div><h3>Previous · Rev {current.old_revision}</h3>{a&&<SourceCanvas revision={a} characteristic={c?.old} zoom={zoom}/>}</div><div className="comparison-selector"><h3>Detected changes</h3>{changes.map((x:D)=><button key={x.id} onClick={()=>setId(x.id)} className={x.id===c?.id?'selected':''}><strong>{x.label}</strong><span>{human(x.type)}</span><small>{x.risk.level} · {Math.round(x.confidence*100)}%</small></button>)}{!changes.length&&<p>No changes match this filter.</p>}</div><div><h3>New · Rev {current.new_revision}</h3>{b&&<SourceCanvas revision={b} characteristic={c?.new} zoom={zoom}/>}</div></div>{c&&<div className="comparison-evidence"><div className="workbench-toolbar"><div><strong>{val(c.old||{label:'Absent'})} → {val(c.new||{label:'Absent'})}</strong><p>Matching: {c.matching_method||'STABLE_ID'} · Human decision: {c.review}</p></div><button className="button primary" onClick={()=>onReview(c)}>Review change</button></div><RuleEvidence change={c}/></div>}</section>
}

function Reconcile({revision,characteristic:c,api,run}:D){
 const [mode,setMode]=useState('SPLIT');const [other,setOther]=useState('');const [reason,setReason]=useState('');
 const [rows,setRows]=useState<D[]>([]);
 const begin=()=>setRows(Array.from({length:mode==='SPLIT'?2:1},(_,i)=>({...c,characteristic_id:c.characteristic_id+(mode==='SPLIT'?'_S'+(i+1):'_M'),label:c.label+(mode==='SPLIT'?' '+(i+1):'')})));
 const update=(i:number,k:string,v:string)=>setRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r));
 return <details className="reconciliation"><summary>Merge / split characteristics</summary><p>Originals are retained as superseded evidence. Replacements require verification.</p><select aria-label="Reconciliation operation" value={mode} onChange={e=>{setMode(e.target.value);setRows([])}}><option>SPLIT</option><option>MERGE</option></select>{mode==='MERGE'&&<select aria-label="Second characteristic" value={other} onChange={e=>setOther(e.target.value)}><option value="">Choose second characteristic</option>{revision.characteristics.filter((x:D)=>x.characteristic_id!==c.characteristic_id&&x.verification_status!=='SUPERSEDED').map((x:D)=><option key={x.characteristic_id} value={x.characteristic_id}>{x.characteristic_id} — {x.label}</option>)}</select>}<button className="button" disabled={mode==='MERGE'&&!other} onClick={begin}>Prepare replacements</button>
 {rows.map((r,i)=><fieldset key={i}><legend>Replacement {i+1}</legend>{['characteristic_id','label','nominal','lower_tolerance','upper_tolerance','unit','raw'].map(k=><label key={k}>{human(k)}<input value={r[k]??''} onChange={e=>update(i,k,e.target.value)}/></label>)}</fieldset>)}{rows.length>0&&<><label>Reconciliation reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button" disabled={reason.length<5} onClick={()=>run(()=>api(`/revisions/${revision.id}/reconcile`,'POST',{expected_version:revision.version,source_ids:mode==='SPLIT'?[c.characteristic_id]:[c.characteristic_id,other],reason,replacements:rows.map(r=>({characteristic_id:r.characteristic_id,label:r.label,type:r.type,nominal:r.nominal===''||r.nominal==null?null:Number(r.nominal),lower_tolerance:r.lower_tolerance===''||r.lower_tolerance==null?null:Number(r.lower_tolerance),upper_tolerance:r.upper_tolerance===''||r.upper_tolerance==null?null:Number(r.upper_tolerance),unit:r.unit,raw:r.raw,critical:r.critical,safety:r.safety,source_page:r.source_page,bbox:r.source_location?.bbox,reason}))}),'Reconciliation saved; verify replacements',false).then((result:D)=>{if(result)setRows([])})}>Save reconciliation</button></>}
 </details>
}

export function ReportExport({id,api}:{id:string,api:Props['api']}){
 const [job,setJob]=useState<D|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!job||!['QUEUED','RUNNING'].includes(job.status))return;const timer=setInterval(()=>api('/jobs/'+job.id).then(setJob).catch((e:Error)=>setError(e.message)),1500);return()=>clearInterval(timer)},[job?.id,job?.status]);
 return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{setJob(await api(`/change-sets/${id}/report-jobs`,'POST',{format:f.get('format'),kind:f.get('kind')}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Report type<select name="kind"><option value="impact">Engineering Change Impact Report</option><option value="comparison">Revision Comparison Report</option><option value="documents">Affected Documents Report</option><option value="actions">Action Report</option><option value="approvals">Approval Report</option></select></label><label className="field">Evidence report format<select name="format"><option value="pdf">PDF engineering impact report</option><option value="xlsx">Excel evidence workbook</option><option value="json">JSON evidence and audit package</option></select></label><p>Captures the current evidence, risk rules, actions, approvals, unresolved items, and complete source/project audit history.</p>{error&&<p role="alert">{error}</p>}{job&&<div className="alert" role="status">Report: {job.status}{job.status==='SUCCEEDED'&&<a className="button primary" href={`/api/v1/jobs/${job.id}/report-download`}>Download report</a>}{job.failure_reason}</div>}<div className="modal-actions"><button className="button primary" disabled={busy||!!job&&['QUEUED','RUNNING'].includes(job.status)}>{busy?'Capturing evidence…':job&&['QUEUED','RUNNING'].includes(job.status)?'Generating report…':'Generate evidence report'}</button></div></form>
}

export function DependencyImport({project,api,run}:D){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<D|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function upload(commit:boolean){if(!file)return;const form=new FormData();form.append('file',file);setBusy(true);setError('');try{const result=await api(`/projects/${project}/dependency-import?commit=${commit}`,'POST',form);setPreview(result);if(commit)await run(async()=>result,'Dependency map imported; review completeness')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div><p>Start without PLM. Convert your process sheet, Control Plan, or PFMEA to a relationship template. Preview before saving; completeness always requires human confirmation.</p><div className="review-buttons">{['process','control-plan','pfmea'].map(k=><a className="button" key={k} href={'/api/v1/templates/'+k}>{human(k)} template</a>)}</div><label className="field">Mapping workbook<input type="file" accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/></label>{error&&<p role="alert">{error}</p>}<button className="button" disabled={!file||busy} onClick={()=>upload(false)}>{busy?'Validating…':'Preview import'}</button>{preview&&<><p>{preview.rows} source rows · {preview.nodes.length} mapped entities · {preview.edges.length} relationships</p><div className="table-scroll"><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th></tr></thead><tbody>{preview.edges.map((e:D,i:number)=><tr key={i}><td>{e.source}</td><td>{e.relation||'Requires review of'}</td><td>{e.target}</td></tr>)}</tbody></table></div><p>Import resets dependency completeness and invalidates existing approvals for unreleased changes.</p><button className="button primary" disabled={busy} onClick={()=>upload(true)}>Save reviewed import</button></>}</div>
}
