import React,{useState} from 'react';
type D=Record<string,any>;
export default function GraphEditor({graph,setGraph}:{graph:string,setGraph:(s:string)=>void}){
 const [node,setNode]=useState({id:'',label:'',type:'material',updated_at:new Date().toISOString().slice(0,10)}),[edge,setEdge]=useState({source:'',target:'',relation:'AFFECTS',evidence:''}),[error,setError]=useState('');
 let data:D;try{data=JSON.parse(graph)}catch{return <p>Correct the JSON structure below before using the mapping builder.</p>}
 const nodes=data.nodes||[],edges=data.edges||[];
 const save=(value:D)=>{setError('');setGraph(JSON.stringify(value,null,2))};
 return <section className="u-map-editor"><h3>Add an entity</h3><p>Use the source row ID to connect a changed field. Edges point from the changed object toward its potential impact.</p><div className="u-two"><label>Stable ID<input value={node.id} onChange={e=>setNode({...node,id:e.target.value})}/></label><label>Entity name<input value={node.label} onChange={e=>setNode({...node,label:e.target.value})}/></label><label>Type<select value={node.type} onChange={e=>setNode({...node,type:e.target.value})}>{['part','feature','characteristic','operation','machine','tool','fixture','inspection','document','supplier','material','product','order','customer','inventory','process','department'].map(t=><option key={t}>{t}</option>)}</select></label><label>Last verified date<input type="date" value={node.updated_at} onChange={e=>setNode({...node,updated_at:e.target.value})}/></label></div><button type="button" onClick={()=>{if(!node.id||!node.label||nodes.some((n:D)=>n.id===node.id)){setError('Enter a unique ID and entity name.');return}save({nodes:[...nodes,{...node,attributes:{}}],edges});setNode({...node,id:'',label:''})}}>Add entity to draft</button><h3 style={{marginTop:20}}>Connect two entities</h3><div className="u-two">{['source','target'].map(side=><label key={side}>{side==='source'?'Changed / upstream object':'Potentially affected object'}<select value={(edge as D)[side]} onChange={e=>setEdge({...edge,[side]:e.target.value})}><option value="">Select an entity</option>{nodes.map((n:D)=><option key={n.id} value={n.id}>{n.id} · {n.label}</option>)}</select></label>)}</div><label>Relationship<select value={edge.relation} onChange={e=>setEdge({...edge,relation:e.target.value})}>{['AFFECTS','DEPENDS_ON','USES','REQUIRES','OWNED_BY','SUPPLIED_BY','REFERENCED_BY','APPROVED_BY','IMPACTS'].map(t=><option key={t}>{t}</option>)}</select></label><label>Mapping evidence<input value={edge.evidence} onChange={e=>setEdge({...edge,evidence:e.target.value})} placeholder="BOM row, process sheet, order or controlled reference"/></label><button type="button" onClick={()=>{if(!edge.source||!edge.target||edge.evidence.length<5){setError('Select both endpoints and provide mapping evidence.');return}save({nodes,edges:[...edges,edge]});setEdge({...edge,evidence:''})}}>Add relationship to draft</button>{error&&<p role="alert">{error}</p>}<p>{nodes.length} entities · {edges.length} relationships in draft. Validate and save below to commit.</p><a href="/api/v1/imports/templates/relationships?format=xlsx">Download relationship Excel template</a></section>
}
