import React,{useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {IconShieldCheck,IconLayoutDashboard,IconGitCompare,IconNetwork,IconChecklist,IconCircleCheck,IconLayersIntersect,IconArrowLeft,IconPlus,IconLogout,IconSettings,IconFileText,IconTool,IconX} from '@tabler/icons-react';
import './universal.css';
import DrawingWorkspace from './drawing-workspace';
import {useWorkspaceRoute} from './workspace-route';
import './workspace.css';
import KnowledgeSearch from './knowledge-search';
import GraphEditor from './graph-editor';
import {EvidenceExport,DependencyUpload,AccessGrants} from './universal-tools';
type D=Record<string,any>;
async function api(path:string,method='GET',body?:any){const r=await fetch('/api/v1'+path,{method,credentials:'same-origin',headers:{'X-ChangeGuard':'1',...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body?body instanceof FormData?body:JSON.stringify(body):undefined});if(!r.ok){const e=await r.json().catch(()=>({detail:r.statusText}));throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r.json()}
const human=(s='')=>s.replaceAll('_',' ').toLowerCase().replace(/^\w/,c=>c.toUpperCase());
const val=(v:any)=>v==null?'Absent':typeof v==='object'?JSON.stringify(v):String(v);
function Badge({value}:{value:string}){return <span className={'u-badge '+(value||'').toLowerCase()}>{human(value)}</span>}
const example=(domain:string)=>domain==='supplier'?[{id:'SUP-17',lead_time_days:7}]:domain==='quality'?[{id:'CP-204',inspection_every_units:100,inspection_sample_count:1}]:[{id:'C27',nominal:20,upper_tolerance:.1,lower_tolerance:-.1,unit:'mm'}];

export default function Universal({me}:{me:D}){
 const qc=useQueryClient();const {route,navigate}=useWorkspaceRoute();const {page,id,tab}=route;const setTab=(tab:string)=>navigate({...route,tab});const [domain,setDomain]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<D|null>(null),[notice,setNotice]=useState('');
 const packs=useQuery<D>({queryKey:['domain-packs'],queryFn:()=>api('/domain-packs')});
 const sets=useQuery<D[]>({queryKey:['universal-list'],queryFn:async()=>{const all:D[]=[];for(let offset=0;;offset+=200){const batch=await api('/workspace/changes?limit=200&offset='+offset);all.push(...batch);if(batch.length<200)return all}}});
 const users=useQuery<D[]>({queryKey:['universal-users'],queryFn:()=>api('/users')});
 const detail=useQuery<D>({queryKey:['universal-change',id],queryFn:()=>api('/workspace/changes/'+id),enabled:!!id});
 const audit=useQuery<D[]>({queryKey:['universal-audit',id],queryFn:async()=>{const all:D[]=[];for(let offset=0;;offset+=1000){const batch=await api('/changes/'+id+'/audit?limit=1000&offset='+offset);all.push(...batch);if(batch.length<1000)return all}},enabled:!!id&&tab==='History'});
 const c=detail.data;const list=(sets.data||[]).filter(x=>(!domain||x.domain===domain)&&(!search||`${x.title} ${x.domain} ${x.status}`.toLowerCase().includes(search.toLowerCase())));const open=list.filter(x=>!['CLOSED','REJECTED','REVERTED','SUPERSEDED','RELEASED'].includes(x.status));
 const owner=(uid:string)=>users.data?.find(x=>x.id===uid)?.name||uid||'Not assigned';
 const canEdit=me.role==='ADMIN'||packs.data?.active.find((p:D)=>p.id===c?.domain)?.edit_roles.includes(me.role);const frozen=!!c&&['APPROVED','EFFECTIVE','CLOSED','REJECTED','REVERTED','SUPERSEDED'].includes(c.status);
 async function run(fn:()=>Promise<any>,message='Saved'){setBusy(true);setError('');try{const result=await fn();await qc.invalidateQueries({queryKey:['universal-list']});await qc.invalidateQueries({queryKey:['universal-change']});await qc.invalidateQueries({queryKey:['universal-audit']});setNotice(message);setModal(null);return result}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function mutate(path:string,data:D,method='POST'){return api('/changes/'+id+path,method,{expected_version:c?.version,...data})}
 function select(x:string,t='Summary'){navigate({page:'Changes',id:x,tab:t});setNotice('')}
 function go(p:string){navigate({page:p,id:null,tab:'Summary'});setNotice('')}
 const confirm=(title:string,path:string,data:D={},method='POST')=>setModal({kind:'reason',title,path,data,method});
 const changeTable=(rows:D[])=> <div className="u-table-wrap"><table><thead><tr><th>Controlled change</th><th>Domain</th><th>Exposure</th><th>Review status</th><th>Owner</th><th>Open actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><button className="u-link" onClick={()=>select(x.id)}>{x.title}</button><small>{x.change_type} · {x.id.slice(0,8)} {x.demo?'· DEMONSTRATION DATA':''}</small></td><td>{human(x.domain)}</td><td><Badge value={x.analysis?.level||'UNASSESSED'}/>{x.analysis&&<small>{x.analysis.score}/100 · rule based</small>}</td><td><Badge value={x.status}/></td><td>{owner(x.owner)}</td><td>{x.actions.filter((a:D)=>a.status!=='COMPLETE').length}</td></tr>)}</tbody></table>{!rows.length&&<div className="u-empty">No changes match this view. Create a controlled change to compare two versions.</div>}</div>;
 if(sets.isPending||packs.isPending)return <div className="loading-screen" role="status"><IconShieldCheck size={38}/><h2>ChangeGuard AI</h2><p>Loading controlled changes and domain policies…</p></div>;
 return <div className="u-shell"><a className="workspace-skip" href="#workspace-main" onClick={e=>{e.preventDefault();document.getElementById('workspace-main')?.focus()}}>Skip to workspace</a><aside className="u-sidebar"><div className="u-brand"><IconShieldCheck size={27}/><div>ChangeGuard <b>AI</b><small>CHANGE & IMPACT INTELLIGENCE</small></div></div><div className="u-company">{me.organization}<small>{me.demo?'DEMONSTRATION DATA':'PRIVATE WORKSPACE'}</small></div><nav>{([['Dashboard',IconLayoutDashboard],['Changes',IconGitCompare],['Compare',IconGitCompare],['Impact map',IconNetwork],['Actions',IconChecklist],['Approvals',IconCircleCheck],['Drawings',IconTool],['Domains',IconLayersIntersect],['Reports',IconFileText],['Knowledge',IconFileText],['Settings',IconSettings]] as const).map(([name,Icon])=><button key={name} aria-current={page===name?'page':undefined} className={page===name?'selected':''} onClick={()=>go(name)}><Icon size={18}/>{name}</button>)}</nav><div className="u-sidebar-bottom"><small>MCCIA AI APPLIED STUDIO</small><strong>{me.name}</strong><span>{human(me.role)} · AI off</span><button onClick={()=>run(async()=>{await api('/auth/logout','POST');window.location.reload()})}><IconLogout size={15}/>Sign out</button></div></aside>
 <main className="u-main" id="workspace-main" tabIndex={-1}><header className="u-top"><span>Industrial AI <span className="subtle">/</span> Change & Impact Intelligence</span><Badge value="PRIVATE · AI OFF"/></header><section className="u-content">
 {error&&<div role="alert" className="u-error">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{notice&&<div role="status" className="u-notice">{notice}</div>}{(sets.error||detail.error)&&<div role="alert" className="u-error">{String(sets.error||detail.error)}</div>}
 {!id?<><div className="u-heading"><div><small>CONTROLLED CHANGE WORKSPACE</small><h1>{page}</h1><p>Know what a change will affect before you approve it.</p></div>{me.role!=='VIEWER'&&<button className="u-primary" onClick={()=>setModal({kind:'create',domain:page==='Drawings'?'engineering':domain,source_type:page==='Drawings'?'DRAWING':'STRUCTURED'})}><IconPlus size={17}/>New change</button>}</div>
 {['Dashboard','Changes','Impact map','Reports','Compare'].includes(page)&&<><div className="u-filters"><input aria-label="Search changes" placeholder="Search changes, domains or status" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter domain" value={domain} onChange={e=>setDomain(e.target.value)}><option value="">All domains</option>{packs.data?.active.map((p:D)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><span>{list.length} visible changes</span></div>{page==='Dashboard'&&<div className="u-kpis">{[['Active changes',open.length],['High / critical exposure',open.filter(x=>['HIGH','CRITICAL'].includes(x.analysis?.level)).length],['Ready for approval',open.filter(x=>x.ready_for_approval||x.status==='READY_FOR_APPROVAL').length],['Mandatory actions open',open.reduce((n,x)=>n+x.actions.filter((a:D)=>a.mandatory&&a.status!=='COMPLETE').length,0)]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div>}{page==='Compare'&&<div className="u-panel"><h2>Current state → proposed state</h2><p>Create a change, select its domain and upload CSV, XLSX or JSON versions. Choose Engineering → Drawing revisions when creating a change for PDFs, images, DOCX and characteristic tables. Both comparison types use this workspace.</p><p>Quick mode calculates changes immediately. Dependency coverage remains unknown until you connect and review mappings.</p></div>}{page==='Impact map'&&<p>Select a change to explore its source-to-impact paths in the Impact tab.</p>}{page==='Reports'&&<p>Select a change, then export its evidence, recommendations, approvals and history as PDF, Excel or JSON.</p>}{changeTable(list)}</>}
 {page==='Actions'&&<div className="u-table-wrap"><table><thead><tr><th>Action</th><th>Change</th><th>Owner</th><th>Due</th><th>Status</th></tr></thead><tbody>{list.flatMap(x=>x.actions.map((a:D)=><tr key={a.id}><td><button className="u-link" onClick={()=>select(x.id,'Actions')}>{a.title}</button></td><td>{x.title}</td><td>{a.owner_name||owner(a.owner)}</td><td>{a.due_date}</td><td><Badge value={a.status}/></td></tr>))}</tbody></table></div>}
 {page==='Approvals'&&<><div className="u-panel"><h2>Human authority at every approval stage</h2><p>Each stage requires a different person. Missing verification, unresolved changes and mandatory actions block approval. Making a change effective is a separate manager decision.</p></div>{changeTable(list.filter(x=>!['CLOSED','REJECTED','REVERTED','SUPERSEDED','RELEASED'].includes(x.status)))}</>}
 {page==='Domains'&&<><div className="u-domain-grid">{packs.data?.active.map((p:D)=><section className="u-panel" key={p.id}><Badge value="AVAILABLE"/><h2>{p.name}</h2><p>{p.description}</p><small>APPROVAL ROUTE</small><p>{p.approvals.map((roles:string[])=>roles.join(' / ')).join(' → ')}</p><a href={'/api/v1/imports/templates/'+p.id+'?format=xlsx'}>Download Excel template</a><details><summary>Traceable domain rules</summary>{p.rules.map((r:D)=><p key={r.id}><b>{r.id}</b><br/>{r.field} · {r.operator} · +{r.points}<br/>Review: {r.review.join(', ')}</p>)}</details></section>)}</div><div className="u-panel"><h2>Planned domain packs</h2><p>These are architecture extension points, not enabled workflows.</p><div className="u-tags">{packs.data?.planned.map((p:D)=><Badge key={p.id} value={p.name+' · PLANNED'}/>)}</div></div></>}
 {page==='Knowledge'&&<KnowledgeSearch/>}{page==='Drawings'&&<DrawingWorkspace me={me} onBack={()=>go('Changes')} onCreated={select}/>}
 {page==='Settings'&&<div className="u-panel"><h2>Private by default</h2><p>External AI is disabled. Comparison, impact rules and reporting work without an LLM. No source data is transmitted to a model provider.</p><p>Commercial changes have separate access restrictions. Employee and sensitive HR records are outside the enabled packs.</p>{me.role==='ADMIN'&&<button onClick={()=>setModal({kind:'settings'})}>Configure exposure points</button>}<DrawingWorkspace me={me} initialPage="Settings" onBack={()=>go('Changes')} onCreated={select}/></div>}</>:
 !c?<div className="u-empty">Loading controlled evidence…</div>:c.workflow==='DRAWING'?<DrawingWorkspace key={c.id} me={me} context={c} initialTab={({Summary:'Overview',Diff:'Drawing Comparison',Impact:'Impact Map',Evidence:'Characteristics',History:'Audit Trail'} as D)[tab]||tab} onBack={()=>go('Changes')} onCreated={select}/>:<>
 <button className="u-back" onClick={()=>go('Changes')}><IconArrowLeft size={16}/>All changes</button><div className="u-heading"><div><div className="u-tags"><Badge value={c.domain}/><Badge value={c.classification}/>{c.demo&&<Badge value="DEMONSTRATION DATA"/>}</div><h1>{c.title}</h1><p>{c.sources.old?.label||'Current version'} → {c.sources.new?.label||'Proposed version'} · {owner(c.owner)} · {human(c.effectivity)} {c.effective_date||c.effectivity_reference}</p></div><Badge value={c.status}/></div>
 <div className="u-tabs" role="tablist">{['Summary','Diff','Impact','Dependencies','Actions','Approvals','Evidence','History'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Summary'&&<><div className="u-summary-grid"><section className="u-panel"><small>CHANGE EXPOSURE SCORE · RULE BASED</small><div className="u-score">{c.analysis?.score??'—'}<span>/ 100</span></div><Badge value={c.analysis?.level||'UNASSESSED'}/><p>Conservative review priority, not probability of loss.</p>{c.analysis?.contributors.map((r:D,i:number)=><div key={i} className="u-contributor"><span><b>{r.rule_id}</b><small>{r.reason}</small></span><strong>+{r.points}</strong></div>)}</section><section className="u-panel"><h2>{c.blockers.length?'Review is blocked':'Evidence gates satisfied'}</h2>{c.blockers.map((b:string)=><p className="u-blocker" key={b}>{b}</p>)}<p>{c.approvals.length} / {c.approval_flow.length} human approval stages complete</p><button onClick={()=>setTab(c.analysis?'Actions':'Evidence')}>{c.analysis?'Review required actions':'Add current and proposed versions'}</button></section></div>{c.analysis&&<section className="u-panel"><h2>Potential business exposure</h2><div className="u-kpis"><div><span>Affected entities</span><strong>{c.analysis.graph.nodes.length}</strong></div><div><span>Relationship types mapped</span><strong>{c.analysis.coverage.present} / {c.analysis.coverage.required}</strong></div><div><span>Inventory quantity</span><strong className="u-value">{c.analysis.business_exposure.inventory_quantity?Object.entries(c.analysis.business_exposure.inventory_quantity).map(([k,v])=>`${v} ${k}`).join(', '):'UNKNOWN'}</strong></div><div><span>Associated order value</span><strong className="u-value">{c.analysis.business_exposure.associated_order_value?Object.entries(c.analysis.business_exposure.associated_order_value).map(([k,v])=>`${k} ${v}`).join(', '):'UNKNOWN'}</strong></div></div><p>{c.analysis.coverage.notice}</p><p>{c.analysis.business_exposure.notice}</p></section>}<section className="u-panel"><h2>Evidence report</h2><p>Includes sources, field changes, recommendations, exposure calculation, actions, approvals and complete audit history.</p><EvidenceExport key={c.id} id={c.id}/></section></>}
 {tab==='Evidence'&&<><div className="u-source-grid">{['old','new'].map(side=><SourcePanel key={c.id+side} side={side} c={c} busy={busy} disabled={!canEdit||frozen} run={run} mutate={mutate} confirm={confirm} edit={(item:D)=>setModal({kind:'correction',side,item})}/>)}</div><div className="u-panel"><h2>Structured comparison</h2><p>Compare verified IDs and normalized fields. Source corrections preserve original values and invalidate earlier analysis.</p><button className="u-primary" disabled={busy||!canEdit||frozen||!c.sources.old||!c.sources.new} onClick={()=>confirm('Compare controlled versions','/compare')}>Compare & analyze impact</button>{c.domain==='engineering'&&c.classification==='INTERNAL'&&<div className="drawing-entry"><h3>Need to compare drawing revisions?</h3><p>Attach PDFs, images or engineering characteristic tables to this change. Drawing verification and release will become its active workflow. Earlier structured evidence stays in history; it will not be copied as verified drawing evidence.</p><button disabled={!['ADMIN','ENGINEER','MANAGER'].includes(me.role)||frozen} onClick={()=>setModal({kind:'drawingSetup'})}>Use drawing revisions for this change</button></div>}</div></>}
 {tab==='Diff'&&(!c.analysis?<div className="u-empty">Add both versions in Evidence, then compare.</div>:<><div className="u-panel"><h2>{c.analysis.deltas.length} detected changes</h2><p>Source confidence refers to extraction, not certainty that every dependency is known. Ignoring a detection preserves its rules and mandatory review actions.</p></div>{c.analysis.deltas.map((d:D)=><section key={d.id} className="u-delta"><header><h3>{d.object_id} / {human(d.field)}</h3><Badge value={d.type}/><Badge value={d.decision}/></header><div className="u-before-after"><div><small>CURRENT</small><strong>{val(d.old_value)}</strong></div><span>→</span><div><small>PROPOSED</small><strong>{val(d.new_value)}</strong></div></div><p>{Math.round(d.confidence*100)}% extraction confidence · {human(d.engine)}</p>{Object.keys(d.metrics||{}).length>0&&<p className="u-calculated">{Object.entries(d.metrics).filter(([k])=>k!=='engine').map(([k,v])=>`${human(k)}: ${v??'undefined for zero baseline'}`).join(' · ')}</p>}<details><summary>Source & rule evidence</summary><pre>{JSON.stringify({source:d.source,rules:d.rules},null,2)}</pre></details>{d.reason&&<p>Review: {d.reason}</p>}<div className="u-tags">{['CONFIRMED','IGNORED','INFORMATIONAL','FLAGGED'].map(decision=><button disabled={busy||!canEdit||frozen} key={decision} onClick={()=>confirm(human(decision)+' change','/deltas/'+d.id+'/review',{decision})}>{human(decision)}</button>)}</div></section>)}</>)}
 {tab==='Impact'&&<Impact c={c}/>}
 {tab==='Dependencies'&&<><div className="u-panel"><h2>Dependency scope & freshness</h2><p>{c.nodes.length} entities · {c.edges.length} directed relationships · {(c.stale_nodes||[]).length} older than 90 days</p><p>Missing types: {c.analysis?.coverage.missing_types.join(', ')||(!c.analysis?'Compare to assess coverage':'None in this pack checklist')}. This checklist cannot establish complete organizational coverage.</p><div className="u-tags"><button disabled={!canEdit||frozen} onClick={()=>setModal({kind:'graph'})}>Edit / import dependency map</button><button disabled={!canEdit||frozen||!c.analysis} onClick={()=>confirm('Confirm scope, missing data and freshness','/graph/verify')}>Record scope review</button></div>{canEdit&&!frozen&&<DependencyUpload c={c} done={()=>run(async()=>true,'Dependency map imported; compare again')}/>} {c.mapping_review&&<p>Reviewed by {c.mapping_review.user}: {c.mapping_review.reason}</p>}</div><div className="u-table-wrap"><table><thead><tr><th>Source</th><th>Relationship</th><th>Potentially affected entity</th><th>Evidence</th></tr></thead><tbody>{c.edges.map((e:D,i:number)=><tr key={i}><td>{e.source}</td><td>{human(e.relation)}</td><td>{e.target}</td><td>{e.evidence}</td></tr>)}</tbody></table></div></>}
 {tab==='Actions'&&<><div className="u-panel"><h2>Required reviews</h2><p>Completion records evidence; it does not change stock, production orders or customer commitments.</p><button disabled={!canEdit||frozen} onClick={()=>setModal({kind:'action'})}>Assign review action</button></div>{c.actions.map((a:D)=><section className="u-delta" key={a.id}><header><h3>{a.title}</h3><Badge value={a.status}/></header><p>{a.reason}</p><small>{owner(a.owner)} · {a.department} · Due {a.due_date} · {a.mandatory?'Mandatory':'Optional'}</small>{a.evidence&&<p>Evidence: {a.evidence}</p>}{a.source&&<details><summary>Recommendation provenance</summary><pre>{JSON.stringify(a.source,null,2)}</pre></details>}<button disabled={frozen||me.role==='VIEWER'||(!['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)&&me.id!==a.owner)} onClick={()=>setModal({kind:'updateAction',action:a})}>Update action</button></section>)}</>}
 {tab==='Approvals'&&<><section className="u-panel"><h2>Can this change proceed?</h2>{c.blockers.map((b:string)=><p className="u-blocker" key={b}>{b}</p>)}{c.approval_flow.map((roles:string[],i:number)=><div className="u-approval" key={i}><b>{i+1}. {roles.join(' / ')}</b><span>{c.approvals[i]?`${c.approvals[i].user} · ${c.approvals[i].at}`:'Independent human approval required'}</span></div>)}<div className="u-tags"><button className="u-primary" disabled={busy||frozen||c.blockers.length>0||!canEdit} onClick={()=>confirm('Approve the next required stage','/approve',{action:'APPROVE'})}>Approve next stage</button><button disabled={busy||c.status!=='APPROVED'||!['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)} onClick={()=>confirm('Confirm effectivity condition has been met','/approve',{action:'MAKE_EFFECTIVE'})}>Make effective</button><button disabled={c.status!=='EFFECTIVE'||!['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)} onClick={()=>confirm('Close with outcome evidence','/approve',{action:'CLOSE'})}>Close change</button></div><p>Approval is bound to a fingerprint of the evidence. Editing an unapproved source, mapping, decision or action clears previous approvals.</p></section><section className="u-panel"><h2>Disposition & learning</h2>{me.role==='ADMIN'&&<AccessGrants c={c} users={users.data||[]}/>}<div className="u-tags">{['REJECT','SUPERSEDE','REVERT'].map(action=><button disabled={!['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)} key={action} onClick={()=>confirm(human(action)+' with rationale','/approve',{action})}>{human(action)}</button>)}<button disabled={!canEdit} onClick={()=>setModal({kind:'feedback'})}>Record feedback</button></div><p>Feedback awaits administrative review. It never changes a rule automatically.</p>{c.feedback.map((f:D,i:number)=><p key={i}>{human(f.outcome)}: {f.reason} · {human(f.status)}</p>)}</section></>}
 {tab==='History'&&<><div className="u-panel"><h2>Change timeline</h2>{c.timeline.map((t:D,i:number)=><p key={i}><b>{human(t.event)}</b> · {t.at} · {t.user}<br/>{t.reason}</p>)}</div>{audit.data?.map((e:D)=><details className="u-audit" key={e.id}><summary>{human(e.operation)} · {e.actor} · {e.at}</summary><pre>{JSON.stringify(e.details,null,2)}</pre></details>)}</>}
 </>}
 </section></main>
 {modal&&<Dialog title={modal.title||({drawingSetup:'Set up drawing revisions',create:'Propose a controlled change',correction:'Correct source value',graph:'Dependency mapping',action:'Assign review action',updateAction:'Update review action',settings:'Configure exposure points',feedback:'Record outcome feedback'} as D)[modal.kind]} close={()=>setModal(null)}>{error&&<p role="alert" className="u-error">{error}</p>}<ModalBody modal={modal} c={c} me={me} users={users.data||[]} packs={packs.data?.active||[]} busy={busy} run={run} mutate={mutate} select={select}/></Dialog>}
 </div>
}

function Dialog({title,close,children}:{title:string,close:()=>void,children:React.ReactNode}){React.useEffect(()=>{const previous=document.activeElement as HTMLElement;const timer=setTimeout(()=>document.querySelector<HTMLElement>('.u-dialog input,.u-dialog textarea,.u-dialog button')?.focus(),0);return()=>{clearTimeout(timer);previous?.focus()}},[]);return <div className="u-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="u-dialog" role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href]')).filter(x=>!x.hasAttribute('disabled'));if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus()}}}}><header><h2>{title}</h2><button aria-label="Close dialog" onClick={close}><IconX size={19}/></button></header>{children}</section></div>}

function SourcePanel({side,c,busy,disabled,run,mutate,confirm,edit}:D){const source=c.sources[side];const [label,setLabel]=useState(side==='old'?'Current':'Proposed'),[rows,setRows]=useState(JSON.stringify(example(c.domain),null,2)),[manual,setManual]=useState(false),[file,setFile]=useState<File|null>(null);return <section className="u-panel"><h2>{side==='old'?'Current / old version':'Proposed / new version'}</h2>{source?<><Badge value={source.verified?'VERIFIED':'REVIEW_REQUIRED'}/><p>{source.label} · {source.filename}</p><a href={'/api/v1/changes/'+c.id+'/sources/'+side+'/download'}>Download controlled source</a><div className="u-table-wrap"><table><thead><tr><th>Object / field</th><th>Value</th><th>Confidence</th><th/></tr></thead><tbody>{source.items.map((x:D)=><tr key={x.id}><td>{x.id}<small>{human(x.engine)} · row {x.source.row??'—'}</small></td><td>{val(x.value)}{x.original_value!==x.value&&<small>Original: {val(x.original_value)}</small>}</td><td>{Math.round(x.confidence*100)}%</td><td><button disabled={disabled} onClick={()=>edit(x)}>Correct</button></td></tr>)}</tbody></table></div><button disabled={disabled||busy||source.verified} onClick={()=>confirm('Verify complete '+side+' source','/sources/'+side+'/verify')}>Verify entire source</button></>:<p>Use a stable id column. Download a <a href={'/api/v1/imports/templates/'+c.domain}>domain template</a>.</p>}<details><summary>{source?'Replace with a controlled source':'Add source version'}</summary><label>Version label<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={40}/></label><label className="u-checkbox"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/>Enter structured rows manually</label>{manual?<textarea aria-label={side+' structured rows'} rows={8} value={rows} onChange={e=>setRows(e.target.value)}/>:<input aria-label={side+' source file'} type="file" accept=".csv,.xlsx,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/>}<button disabled={disabled||busy||(!manual&&!file)} onClick={()=>run(async()=>{if(manual)return mutate('/sources/'+side,{label,rows:JSON.parse(rows),reason:'Controlled structured source entered for review'},'PUT');const data=new FormData();data.append('file',file!);return api('/changes/'+c.id+'/sources/'+side+'/upload?'+new URLSearchParams({label,expected_version:String(c.version),reason:'Controlled source uploaded for review'}),'POST',data)},'Source available for verification')}>{busy?'Processing source…':'Save source for review'}</button></details></section>}

function Impact({c}:{c:D}){const [selected,setSelected]=useState(''),[mode,setMode]=useState('Map');const graph=c.analysis?.graph;if(!graph)return <div className="u-empty">Compare both versions to build the impact map.</div>;const node=graph.nodes.find((n:D)=>n.id===selected);const labels=Object.fromEntries(graph.nodes.map((n:D)=>[n.id,n.label]));const levels:D={};graph.nodes.forEach((n:D)=>{const depth=(graph.paths[n.id]?.[0]?.nodes.length||1)-1;(levels[depth]??=[]).push(n)});return <><div className="u-panel"><div className="u-heading"><div><h2>Change Impact Map</h2><p>Follow mapped relationships from the changed source to potentially affected entities.</p></div><select aria-label="Impact display" value={mode} onChange={e=>setMode(e.target.value)}><option>Map</option><option>Table</option></select></div>{graph.nodes.length===0&&<p className="u-blocker">Organization dependency data not connected. Impact outside the changed fields is UNKNOWN.</p>}{graph.truncated&&<p className="u-blocker">Graph truncated at configured depth or node limit. Approval remains blocked.</p>}{mode==='Map'?<div className="u-graph">{Object.entries(levels).map(([depth,nodes])=><div key={depth} className="u-graph-level"><small>{depth==='0'?'CHANGED SOURCE':'DEPENDENCY HOP '+depth}</small>{nodes.map((n:D)=><button className={'u-node '+(selected===n.id?'selected':'')} key={n.id} onClick={()=>setSelected(n.id)}><small>{human(n.type)}</small><strong>{n.label}</strong><span>{n.id}</span></button>)}</div>)}</div>:<div className="u-table-wrap"><table><thead><tr><th>Entity</th><th>Type</th><th>Source-to-impact path</th></tr></thead><tbody>{graph.nodes.map((n:D)=><tr key={n.id}><td><button className="u-link" onClick={()=>setSelected(n.id)}>{n.label}</button></td><td>{n.type}</td><td>{graph.paths[n.id]?.[0]?.nodes.map((p:string)=>labels[p]||p).join(' → ')}</td></tr>)}</tbody></table></div>}<p>Columns show shortest-path depth. They do not imply that every adjacent card is connected. Select an entity for its actual relationships.</p></div>{node&&<section className="u-panel"><h2>Why {node.label} may be affected</h2>{(graph.paths[node.id]||[]).map((p:D,i:number)=><p className="u-path" key={i}>{p.nodes.map((n:string,j:number)=><React.Fragment key={j}><b>{labels[n]||n}</b>{j<p.relations.length&&<span> — {human(p.relations[j])} → </span>}</React.Fragment>)}</p>)}<p>Updated: {node.updated_at} · Owner: {node.owner||'Not assigned'}</p><p>{graph.path_policy}</p>{graph.edges.filter((e:D)=>e.source===node.id||e.target===node.id).map((e:D,i:number)=><p key={i}>{e.source} → {e.target}: {e.evidence}</p>)}</section>}</>}

function ModalBody({modal:m,c,me,users,packs,busy,run,mutate,select}:D){const [domain,setDomain]=useState(m.domain||packs.find((p:D)=>me.role==='ADMIN'||p.edit_roles.includes(me.role))?.id||'engineering'),[graph,setGraph]=useState(JSON.stringify({nodes:c?.nodes||[],edges:c?.edges||[]},null,2)),[preview,setPreview]=useState<D|null>(null),[points,setPoints]=useState('{}');const currentSettings=useQuery<D>({queryKey:['domain-settings-editor'],queryFn:()=>api('/domain-settings'),enabled:m.kind==='settings'});React.useEffect(()=>{if(currentSettings.data)setPoints(JSON.stringify(currentSettings.data.rule_points,null,2))},[currentSettings.data]);return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const reason=String(f.get('reason')||'');run(async()=>{if(m.kind==='reason')return mutate(m.path,{...m.data,reason},m.method);if(m.kind==='create'){if(domain==='engineering'&&f.get('source_type')==='DRAWING'){if(String(f.get('part')||'').trim().length<2)throw new Error('Enter a controlled part number for the drawing revisions.');if(f.get('classification')!=='INTERNAL')throw new Error('Drawing changes currently require Internal classification.');}const result=await api('/changes','POST',{title:f.get('title'),domain,owner:f.get('owner'),reason,description:f.get('description'),classification:f.get('classification'),mode:f.get('mode'),effectivity:f.get('effectivity'),effective_date:f.get('effective_date')||null,effectivity_reference:f.get('reference')||''});select(result.id,'Evidence');if(domain==='engineering'&&f.get('source_type')==='DRAWING'){await api('/workspace/changes/'+result.id+'/drawing-workspace','POST',{part:f.get('part'),customer:f.get('customer'),expected_version:result.version,reason});select(result.id,'Summary')}return result}if(m.kind==='drawingSetup')return api('/workspace/changes/'+c.id+'/drawing-workspace','POST',{part:f.get('part'),customer:f.get('customer'),expected_version:c.version,reason});if(m.kind==='correction')return mutate('/sources/'+m.side+'/correction',{item_id:m.item.id,value:f.get('value'),reason},'PATCH');if(m.kind==='graph')return mutate('/graph',{...JSON.parse(graph),reason},'PUT');if(m.kind==='action')return mutate('/actions',{title:f.get('title'),owner:f.get('owner'),department:f.get('department'),due_date:f.get('due'),reason});if(m.kind==='updateAction')return mutate('/actions/'+m.action.id,{status:f.get('status'),evidence:f.get('evidence'),reason,...(['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)?{owner:f.get('owner')}:{} )},'PATCH');if(m.kind==='feedback')return mutate('/feedback',{outcome:f.get('outcome'),reason});if(m.kind==='settings'){return api('/domain-settings','PUT',{expected_version:currentSettings.data?.version,rule_points:JSON.parse(points),reason})}})}}>
 {m.kind==='drawingSetup'&&<><p>Current drawing evidence will control this change's reviews and release. Original structured sources and decisions remain in the audit history.</p><label>Controlled part number<input name="part" required minLength={2} maxLength={100}/></label><label>Customer / program<input name="customer" maxLength={160}/></label></>}{m.kind==='create'&&<>{domain==='engineering'&&<><label>Source type<select name="source_type" defaultValue={m.source_type||'STRUCTURED'}><option value="STRUCTURED">Structured records · CSV / XLSX / JSON</option><option value="DRAWING" disabled={!['ADMIN','ENGINEER','MANAGER'].includes(me.role)}>Drawing revisions · PDF / image / DOCX / characteristic table</option></select></label><label>Controlled part number (required for drawings)<input name="part" minLength={2} maxLength={100}/></label><label>Customer / program<input name="customer" maxLength={160}/></label></>}<label>Title<input required name="title" minLength={4} maxLength={160} placeholder="Supplier lead time: 7 → 14 days"/></label><label>Domain<select value={domain} onChange={e=>setDomain(e.target.value)}>{packs.filter((p:D)=>me.role==='ADMIN'||p.edit_roles.includes(me.role)).map((p:D)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Owner<select name="owner" defaultValue={me.id}>{users.map((u:D)=><option value={u.id} key={u.id}>{u.name} · {u.role}</option>)}</select></label><label>Description<textarea name="description" maxLength={2000}/></label><label>Mode<select name="mode"><option value="QUICK">Quick · dependency data not yet connected</option><option value="CONNECTED">Connected · import a reviewed dependency map</option></select></label><label>Access classification<select name="classification"><option>INTERNAL</option><option>COMMERCIAL</option></select></label><label>Effectivity<select name="effectivity">{['IMMEDIATE','DATE','NEXT_BATCH','NEXT_ORDER','AFTER_WIP','SPECIFIC_REVISION'].map(x=><option key={x}>{x}</option>)}</select></label><div className="u-two"><label>Effective date<input name="effective_date" type="date"/></label><label>Batch / order / revision reference<input name="reference" maxLength={160}/></label></div></>}
 {m.kind==='correction'&&<><p>{m.item.id} · Original evidence retained</p><label>Corrected value<input name="value" required defaultValue={m.item.value} maxLength={4000}/></label></>}
 {m.kind==='graph'&&<><GraphEditor graph={graph} setGraph={value=>{setGraph(value);setPreview(null)}}/><p>Import a JSON map with nodes and directed edges. Each node requires id, label, type and updated_at. Each edge requires source, target, relation and evidence. Only bounded, explicit mappings are accepted.</p><label>Load map<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f){setGraph(await f.text());setPreview(null)}}}/></label><textarea aria-label="Dependency map JSON" rows={15} value={graph} onChange={e=>{setGraph(e.target.value);setPreview(null)}}/><button type="button" onClick={async()=>{try{setPreview(await mutate('/graph?preview=true',{...JSON.parse(graph),reason:'Dependency import validation preview'},'PUT'))}catch(e){setPreview({error:(e as Error).message})}}}>Validate preview</button>{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}</>}
 {m.kind==='action'&&<><label>Required review<input name="title" required minLength={5}/></label><label>Owner<select name="owner">{users.map((u:D)=><option value={u.id} key={u.id}>{u.name} · {u.role}</option>)}</select></label><label>Department<input name="department" required defaultValue={c.domain}/></label><label>Due date<input name="due" type="date" required/></label></>}
 {m.kind==='updateAction'&&<><p>{m.action.title}</p><label>Status<select name="status" defaultValue={m.action.status}>{['OPEN','IN_PROGRESS','COMPLETE'].map(x=><option key={x}>{x}</option>)}</select></label>{['ADMIN','MANAGER','MANAGEMENT'].includes(me.role)&&<label>Owner<select name="owner" defaultValue={m.action.owner}>{users.map((u:D)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label>}<label>Verification evidence<textarea name="evidence" defaultValue={m.action.evidence} maxLength={2000} placeholder="Record the reviewed document, result and reference."/></label></>}
 {m.kind==='feedback'&&<label>Outcome<select name="outcome">{['USEFUL','NOT_USEFUL','INCORRECT','MISSING_IMPACT'].map(x=><option key={x}>{x}</option>)}</select></label>}
 {m.kind==='settings'&&<><p>Provide rule IDs and point values from 1–100. Saving invalidates analysis and approvals on open changes. Approved evidence remains frozen. Example: {`{"SUP-LEAD-001":40}`}</p><textarea rows={6} aria-label="Rule point overrides" value={points} onChange={e=>setPoints(e.target.value)}/></>}
 <label>Reason / review evidence<textarea name="reason" required minLength={5} maxLength={1000} placeholder="Explain the decision and cite supporting evidence."/></label><button className="u-primary" disabled={busy||(m.kind==='graph'&&!preview?.valid)}>{busy?'Saving…':'Save controlled decision'}</button>
 </form>}
